# Generated by Django 3.0.4 on 2020-03-15 04:18

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsksalon', '0002_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('short_description', ckeditor.fields.RichTextField(default='Blog Short Description')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(default='Blog Long Description')),
            ],
        ),
    ]
