# Generated by Django 3.0.4 on 2020-03-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsksalon', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='this is a test produtc'),
            preserve_default=False,
        ),
    ]
