# Generated by Django 3.0.4 on 2020-03-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsksalon', '0005_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='this is a test'),
            preserve_default=False,
        ),
    ]
