# Generated by Django 3.0.4 on 2020-03-15 08:57

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsksalon', '0006_course_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beauty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('short_description', ckeditor.fields.RichTextField(default='Course Short Descriptions')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(default='Couuse Long Descriptions')),
                ('slug', models.SlugField()),
            ],
        ),
    ]
