# Generated by Django 3.0.4 on 2020-03-15 09:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsksalon', '0007_beauty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bridal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('description', ckeditor.fields.RichTextField(default='this is a single line details of image')),
            ],
        ),
        migrations.CreateModel(
            name='Nail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('description', ckeditor.fields.RichTextField(default='this is a single line details of image')),
            ],
        ),
        migrations.CreateModel(
            name='Tattoo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('description', ckeditor.fields.RichTextField(default='this is a single line details of image')),
            ],
        ),
    ]
